// Tech Skill Vocabulary - Master list of all tech skills

export const TECH_SKILL_VOCABULARY = [
  // Frontend Skills
  'React',
  'Vue',
  'Angular',
  'TypeScript',
  'JavaScript',
  'HTML',
  'CSS',
  'SCSS',
  'Webpack',
  'Next.js',
  'Gatsby',
  'Redux',
  'MobX',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Jest',
  'React Testing Library',
  'Cypress',
  'Storybook',
  'WebAssembly',
  'PWA',
  'GraphQL',

  // Backend Skills
  'Node.js',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'Java',
  'Spring Boot',
  'Go',
  'Rust',
  'C++',
  'C#',
  '.NET',
  'ASP.NET',
  'PHP',
  'Laravel',
  'Ruby',
  'Rails',
  'Express',
  'Fastify',
  'NestJS',
  'Scala',
  'Kotlin',

  // Database Skills
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'Elasticsearch',
  'DynamoDB',
  'Firebase',
  'Cassandra',
  'Oracle',
  'SQL Server',
  'Neo4j',
  'CouchDB',
  'MariaDB',
  'SQLite',

  // DevOps & Cloud
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'Terraform',
  'Ansible',
  'Jenkins',
  'GitLab CI',
  'GitHub Actions',
  'CircleCI',
  'CloudFormation',
  'Docker Compose',
  'Nginx',
  'Apache',
  'Linux',
  'Ubuntu',
  'CentOS',

  // Data & ML
  'Python',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Plotly',
  'Apache Spark',
  'Hadoop',
  'SQL',
  'Airflow',
  'Datadog',
  'Tableau',
  'Power BI',

  // Mobile Development
  'React Native',
  'Flutter',
  'Swift',
  'Kotlin',
  'Java Android',
  'Objective-C',
  'Expo',
  'Ionic',
  'Xamarin',

  // Tools & Utilities
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'NPM',
  'Yarn',
  'Maven',
  'Gradle',
  'Pip',
  'Docker Hub',
  'REST APIs',
  'gRPC',
  'Protocol Buffers',
  'SOAP',
  'WebSockets',

  // Soft Skills
  'Leadership',
  'Communication',
  'Problem Solving',
  'Team Collaboration',
  'Code Review',
  'Documentation',
  'Agile',
  'Scrum',
  'Kanban',
  'Project Management',
  'System Design',
  'Microservices',
  'SOLID Principles',
  'Design Patterns',
  'API Design',
  'Scalability',
  'Performance Optimization',
  'Security',
  'CI/CD',
  'Testing',
  'Debugging',
]

export const EDUCATION_LEVELS = {
  'High School': 0,
  'Associate': 1,
  "Bachelor's": 2,
  "Master's": 3,
  'PhD': 4,
}

export const SENIORITY_LEVELS = {
  'Entry Level': 0.2,
  'Junior': 0.3,
  'Mid-Level': 0.5,
  'Senior': 0.7,
  'Staff': 0.85,
  'Principal': 1.0,
}

// Map skill names to canonical form
export const SKILL_ALIASES: Record<string, string> = {
  'react.js': 'React',
  'reactjs': 'React',
  'vue.js': 'Vue',
  'vuejs': 'Vue',
  'angular.js': 'Angular',
  'angularjs': 'Angular',
  'typescript': 'TypeScript',
  'ts': 'TypeScript',
  'javascript': 'JavaScript',
  'js': 'JavaScript',
  'node': 'Node.js',
  'nodejs': 'Node.js',
  'node.js': 'Node.js',
  'postgres': 'PostgreSQL',
  'postgresql': 'PostgreSQL',
  'mongo': 'MongoDB',
  'mongodb': 'MongoDB',
  'aws': 'AWS',
  'amazon web services': 'AWS',
  'gcp': 'GCP',
  'google cloud': 'GCP',
  'azure': 'Azure',
  'k8s': 'Kubernetes',
  'kubernetes': 'Kubernetes',
  'docker': 'Docker',
  'ml': 'Machine Learning',
  'ai': 'Artificial Intelligence',
  'python': 'Python',
  'java': 'Java',
  'go': 'Go',
  'golang': 'Go',
  'rust': 'Rust',
  'c++': 'C++',
  'cpp': 'C++',
  'c#': 'C#',
  'csharp': 'C#',
  'dotnet': '.NET',
  '.net': '.NET',
  'html5': 'HTML',
  'css3': 'CSS',
  'rest': 'REST APIs',
  'rest api': 'REST APIs',
  'graphql': 'GraphQL',
  'git': 'Git',
  'github': 'Git',
  'gitlab': 'Git',
  'bitbucket': 'Git',
  'cicd': 'CI/CD',
  'ci/cd': 'CI/CD',
  'jenkins': 'Jenkins',
  'docker compose': 'Docker',
  'docker-compose': 'Docker',
  'terraform': 'Terraform',
  'ansible': 'Ansible',
  'nginx': 'Nginx',
  'apache': 'Apache',
  'linux': 'Linux',
  'ubuntu': 'Linux',
  'centos': 'Linux',
  'sql': 'SQL',
  'mysql': 'MySQL',
  'mariadb': 'MySQL',
  'redis': 'Redis',
  'elasticsearch': 'Elasticsearch',
  'react native': 'React Native',
  'reactnative': 'React Native',
  'flutter': 'Flutter',
  'swift': 'Swift',
  'kotlin': 'Kotlin',
  'android': 'Java Android',
  'objective-c': 'Objective-C',
  'leadership': 'Leadership',
  'communication': 'Communication',
  'problem solving': 'Problem Solving',
  'scrum': 'Scrum',
  'agile': 'Agile',
  'system design': 'System Design',
  'microservices': 'Microservices',
  'testing': 'Testing',
  'jest': 'Jest',
  'cypress': 'Cypress',
  'storybook': 'Storybook',
}

// Get canonical skill name
export function normalizeSkillName(skill: string): string {
  const trimmed = skill.toLowerCase().trim()
  return SKILL_ALIASES[trimmed] || skill
}
